### PR TITLE
Header style changed

### PR DESCRIPTION
**Pull request by MargaritaLoseva**
Agreed with Dmitry Kharkov
/cc @inikulin, @VasilyStrelyaev

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
FYI:
Before
image

After
image

**Comment by inikulin** [comment]
lgtm

**Comment by MargaritaLoseva** [comment]
@inikulin  Please, close this pull request

**Comment by inikulin** [comment]
@MargaritaLoseva Close or merge?

**Comment by inikulin** [comment]
@MargaritaLoseva Close or merge?

**Comment by MargaritaLoseva** [comment]
@inikulin Merge

**Pull request merged**
