### PR TITLE
Introduce Note and Important boxes

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
This PR introduces nice boxes for critical and reference information:
i37 cimgpsh_orig
i38 cimgpsh_orig

**How to use:**

* Note box

```
> Here is some
> reference information
```

* Important box

```
> Important! This information is
> of critical importance
```

The `Important! ` text serves as the marker in the latter case. It's displayed 'as is' when viewing the file in the GH repo, while on the website it's removed in favor of the Important icon.

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
\cc @DevExpress/testcafe-docs

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm. Can you please add note to the issue title how it should be used from markdown?

**Comment by VasilyStrelyaev** [comment]
@inikulin sure, done

**Comment by MargaritaLoseva** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
ping @churkin

**Comment by VasilyStrelyaev** [comment]
oh, where are you, @churkin ?

**Comment by inikulin** [comment]
@VasilyStrelyaev he is to your left

**Comment by VasilyStrelyaev** [comment]
Can we go without @churkin ?
He seems to be sabotaging the review =)

**Comment by inikulin** [comment]
Just tell him to review personally already =)

**Comment by inikulin** [comment]
And you can go without him =)

**Comment by churkin** [comment]
lgtm

**Pull request merged**
