### PR TITLE
Introduce the Landing page

### PR DESCRIPTION
**Pull request by MargaritaLoseva**
\cc @DevExpress/testcafe-docs

These are styles and scripts for the landing page. The page markup is here - https://github.com/DevExpress/testcafe/pull/682

Closes https://github.com/DevExpress/testcafe/issues/297

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
Let me deploy it for the folks:
[http://strelyaev-w8:8080/testcafe/](http://strelyaev-w8:8080/testcafe/)

**Comment by MargaritaLoseva** [comment]
fpr

**Comment by VasilyStrelyaev** [comment]
And I no longer have it deployed... See [http://loseva-w8:8080/testcafe/](http://loseva-w8:8080/testcafe/)

**Comment by VasilyStrelyaev** [comment]
Maybe it makes sense to rebase it on DevExpress/testcafe-gh-page-assets#11 once it lands and then see how it looks...
We may need to increase the `banner`'s padding

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by inikulin** [comment]
Can we have this all in #682? It's hard to review it in separate PRs

**Comment by VasilyStrelyaev** [comment]
mmm... these are different repos. BTW

**Comment by inikulin** [comment]
Oh, got it =))

**Comment by inikulin** [comment]
I'd like to see #11 merged first and this rebased on top of it, then

**Comment by MargaritaLoseva** [comment]
I've rebased on top of [#11](https://github.com/DevExpress/testcafe-gh-page-assets/pull/11)

FPR

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Pull request merged**
