### PR TITLE
Make the landing page load faster

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
\cc @DevExpress/testcafe-docs 

fixes https://github.com/DevExpress/testcafe-gh-page-assets/issues/13

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
see [http://strelyaev-w8:9090/testcafe/](http://strelyaev-w8:9090/testcafe/)

**Comment by MargaritaLoseva** [comment]
lgtm

**Comment by kirovboris** [comment]
Please fix "jumping" of github widget 
/r-

**Comment by VasilyStrelyaev** [comment]
You mean the background resizing? 
'cause the widget doesn't jump anywhere itself

**Comment by kirovboris** [comment]
Yep

**Comment by VasilyStrelyaev** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
